### ISSUE TITLE
Ability to update and delete found objects

### ISSUE THREAD

**Issue by Wyzix33** [moinism/faltu#3]
Hi, i am interested in updating, deleting all or only search result(s), is this posible?
eq:
```
newData= new Faltu(data).find({
  age: 18
}).update(age:19).get();
```

newData would contain the  rows found in data but with the updated value for age, 19 instead of 18...

and also the ability to delete:
```
newData = new Faltu(data).find({
  age: 19
}).delete().get();
```
or maybe even use delete instead of find:

```
newData = new Faltu(data).delete({
  age: 19
}).get();
```
here newdata will be an array with the deleted rows.
It would be nice if Sorting, Limit, Skip, Skip & Limit, Unique, Filtering and Iterate would work with update and delete too :)

Thanks

**Comment by moinism** [comment]
@Wyzix33 Faltu is only for data search operations and I do not intend to add any manipulation methods to it.
Have a look at [ChotaDB](https://github.com/moinism/chotadb), might help.
